export const WORLDS = [
  {
    id: 'dino-wilds',
    name: 'The Dino-Wilds',
    emoji: '🦕',
    guide: 'Rex the Raptor',
    guideEmoji: '🦖',
    primaryColor: '#2D5A27',
    secondaryColor: '#8BC34A',
    accentColor: '#FF6B35',
    bgColor: '#1A3A17',
    textColor: '#E8F5E9',
    buttonColor: '#4CAF50',
    terms: {
      quest: 'Hunt',
      hero: 'Hunter',
      relic: 'Fossil',
      hint: 'Raptor Roar',
      complete: 'Extinction Event',
      stage1: 'The Tracking',
      stage2: 'The Hunt',
      stage3: 'The Triumph',
    },
    guideGreeting: "RAWR! Ready to hunt some knowledge, Hunter?",
  },
  {
    id: 'minecraftia',
    name: 'Minecraftia',
    emoji: '⛏️',
    guide: 'Steve',
    guideEmoji: '🧱',
    primaryColor: '#4E342E',
    secondaryColor: '#8D6E63',
    accentColor: '#4CAF50',
    bgColor: '#1B0000',
    textColor: '#F5F5DC',
    buttonColor: '#4CAF50',
    terms: {
      quest: 'Build Mission',
      hero: 'Crafter',
      relic: 'Diamond',
      hint: 'Redstone Clue',
      complete: 'Achievement Unlocked',
      stage1: 'Mining Phase',
      stage2: 'Building Phase',
      stage3: 'Victory Lap',
    },
    guideGreeting: "Time to craft some knowledge, Crafter!",
  },
  {
    id: 'vacuum-city',
    name: 'Vacuum City',
    emoji: '🤖',
    guide: 'Vac-9000',
    guideEmoji: '🌀',
    primaryColor: '#1565C0',
    secondaryColor: '#42A5F5',
    accentColor: '#FF4081',
    bgColor: '#0D1B2A',
    textColor: '#E3F2FD',
    buttonColor: '#2196F3',
    terms: {
      quest: 'Clean Protocol',
      hero: 'Commander',
      relic: 'Power Cell',
      hint: 'Sensor Ping',
      complete: 'Area Cleaned',
      stage1: 'Scanning',
      stage2: 'Cleaning',
      stage3: 'Docked',
    },
    guideGreeting: "BEEP-BOOP! Ready to clean up this homework, Commander?",
  },
  {
    id: 'space-rangers',
    name: 'Space Rangers',
    emoji: '🚀',
    guide: 'Captain Nova',
    guideEmoji: '👨‍🚀',
    primaryColor: '#4A148C',
    secondaryColor: '#7B1FA2',
    accentColor: '#FFD700',
    bgColor: '#0A0A1A',
    textColor: '#E8EAF6',
    buttonColor: '#9C27B0',
    terms: {
      quest: 'Mission',
      hero: 'Ranger',
      relic: 'Star Medal',
      hint: 'Cosmic Clue',
      complete: 'Mission Complete',
      stage1: 'Launch',
      stage2: 'Orbit',
      stage3: 'Landing',
    },
    guideGreeting: "3... 2... 1... Let's blast off into learning, Ranger!",
  },
  {
    id: 'pirate-seas',
    name: 'Pirate Seas',
    emoji: '🏴‍☠️',
    guide: "Cap'n Byte",
    guideEmoji: '🦜',
    primaryColor: '#37474F',
    secondaryColor: '#78909C',
    accentColor: '#FFD700',
    bgColor: '#1A237E',
    textColor: '#ECEFF1',
    buttonColor: '#FF9800',
    terms: {
      quest: 'Voyage',
      hero: 'Buccaneer',
      relic: 'Gold Doubloon',
      hint: 'Treasure Map',
      complete: 'Land Ahoy',
      stage1: 'Cast Off',
      stage2: 'High Seas',
      stage3: 'Port Arrival',
    },
    guideGreeting: "Arrr! The seas of knowledge await ye, Buccaneer!",
  },
];

export const LEARNING_STYLES = [
  { id: 'read',        label: 'I like to read',      emoji: '📖', description: 'Text-based quests' },
  { id: 'visual',     label: 'Show me pictures',     emoji: '🎨', description: 'Image-heavy quests' },
  { id: 'audio',      label: 'Tell me a story',      emoji: '🎧', description: 'Audio narrated quests' },
  { id: 'interactive',label: 'Make it a game',        emoji: '🎮', description: 'Interactive challenges' },
];
