export const WORLDS = [
  {
    id: 'dino-wilds',
    name: 'The Dino-Wilds',
    emoji: '🦕',
    guide: 'Rex the Raptor',
    guideEmoji: '🦖',
    /* bright warm jungle — light cream to soft green */
    primaryColor: '#2E7D32',
    secondaryColor: '#81C784',
    accentColor:  '#FF7043',
    bgColor:      '#F1F8E9',
    textColor:    '#1B5E20',
    buttonColor:  '#43A047',
    cardBg:       '#FFFFFF',
    headerBg:     '#2E7D32',
    headerText:   '#FFFFFF',
    terms: {
      quest: 'Hunt',
      hero: 'Hunter',
      relic: 'Fossil',
      hint: 'Raptor Roar',
      complete: 'Extinction Event',
      stage1: 'The Tracking',
      stage2: 'The Hunt',
      stage3: 'The Triumph',
    },
    guideGreeting: "RAWR! Ready to hunt some knowledge, Hunter?",
  },
  {
    id: 'minecraftia',
    name: 'Minecraftia',
    emoji: '⛏️',
    guide: 'Steve',
    guideEmoji: '🧱',
    /* warm cream/amber to earthy brown */
    primaryColor: '#5D4037',
    secondaryColor: '#8D6E63',
    accentColor:  '#33691E',
    bgColor:      '#FFF8E1',
    textColor:    '#3E2723',
    buttonColor:  '#558B2F',
    cardBg:       '#FFFFFF',
    headerBg:     '#5D4037',
    headerText:   '#FFFFFF',
    terms: {
      quest: 'Build Mission',
      hero: 'Crafter',
      relic: 'Diamond',
      hint: 'Redstone Clue',
      complete: 'Achievement Unlocked',
      stage1: 'Mining Phase',
      stage2: 'Building Phase',
      stage3: 'Victory Lap',
    },
    guideGreeting: "Time to craft some knowledge, Crafter!",
  },
  {
    id: 'vacuum-city',
    name: 'Vacuum City',
    emoji: '🤖',
    guide: 'Vac-9000',
    guideEmoji: '🌀',
    /* sky blue to bright blue — airy & clean */
    primaryColor: '#1565C0',
    secondaryColor: '#42A5F5',
    accentColor:  '#FF4081',
    bgColor:      '#E3F2FD',
    textColor:    '#0D47A1',
    buttonColor:  '#1E88E5',
    cardBg:       '#FFFFFF',
    headerBg:     '#1565C0',
    headerText:   '#FFFFFF',
    terms: {
      quest: 'Clean Protocol',
      hero: 'Commander',
      relic: 'Power Cell',
      hint: 'Sensor Ping',
      complete: 'Area Cleaned',
      stage1: 'Scanning',
      stage2: 'Cleaning',
      stage3: 'Docked',
    },
    guideGreeting: "BEEP-BOOP! Ready to clean up this homework, Commander?",
  },
  {
    id: 'space-rangers',
    name: 'Space Rangers',
    emoji: '🚀',
    guide: 'Captain Nova',
    guideEmoji: '👨‍🚀',
    /* soft lavender to deep purple — cosmic but bright */
    primaryColor: '#6A1B9A',
    secondaryColor: '#AB47BC',
    accentColor:  '#FFD740',
    bgColor:      '#EDE7F6',
    textColor:    '#4A148C',
    buttonColor:  '#AB47BC',
    cardBg:       '#FFFFFF',
    headerBg:     '#6A1B9A',
    headerText:   '#FFFFFF',
    terms: {
      quest: 'Mission',
      hero: 'Ranger',
      relic: 'Star Medal',
      hint: 'Cosmic Clue',
      complete: 'Mission Complete',
      stage1: 'Launch',
      stage2: 'Orbit',
      stage3: 'Landing',
    },
    guideGreeting: "3... 2... 1... Let's blast off into learning, Ranger!",
  },
  {
    id: 'pirate-seas',
    name: 'Pirate Seas',
    emoji: '🏴‍☠️',
    guide: "Cap'n Byte",
    guideEmoji: '🦜',
    /* light cyan/turquoise to deep teal — warm ocean */
    primaryColor: '#00695C',
    secondaryColor: '#4DB6AC',
    accentColor:  '#FFD740',
    bgColor:      '#E0F7FA',
    textColor:    '#004D40',
    buttonColor:  '#FF8F00',
    cardBg:       '#FFFFFF',
    headerBg:     '#00695C',
    headerText:   '#FFFFFF',
    terms: {
      quest: 'Voyage',
      hero: 'Buccaneer',
      relic: 'Gold Doubloon',
      hint: 'Treasure Map',
      complete: 'Land Ahoy',
      stage1: 'Cast Off',
      stage2: 'High Seas',
      stage3: 'Port Arrival',
    },
    guideGreeting: "Arrr! The seas of knowledge await ye, Buccaneer!",
  },
];

export const LEARNING_STYLES = [
  { id: 'read',        label: 'I like to read',      emoji: '📖', description: 'Text-based quests' },
  { id: 'visual',     label: 'Show me pictures',     emoji: '🎨', description: 'Image-heavy quests' },
  { id: 'audio',      label: 'Tell me a story',      emoji: '🎧', description: 'Audio narrated quests' },
  { id: 'interactive',label: 'Make it a game',        emoji: '🎮', description: 'Interactive challenges' },
];
