export const EMERGENCY_MESSAGES = [
  "Take a deep breath. You've got this.",
  "Every hero needs a rest. That's okay!",
  "The quest will wait for you. No rush.",
  "You're braver than you believe.",
  "Even Rex the Raptor takes breaks!",
];

export function getRandomEmergencyMessage() {
  return EMERGENCY_MESSAGES[Math.floor(Math.random() * EMERGENCY_MESSAGES.length)];
}

export function buildPrintableHTML(quest, world, heroName) {
  const name = heroName || world.terms.hero;
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>QuestLens — ${quest.questTitle || 'Quest Map'}</title>
  <style>
    body { font-family: Arial, sans-serif; padding: 24px; color: #1a1a1a; }
    h1   { color: ${world.primaryColor}; font-size: 24px; margin-bottom: 4px; }
    .hero{ font-size: 14px; color: #555; margin-bottom: 16px; }
    .stage { border: 2px solid ${world.accentColor}; border-radius: 8px; padding: 12px; margin-bottom: 12px; }
    .stage-title { font-weight: bold; font-size: 16px; color: ${world.primaryColor}; }
    .stage-body  { font-size: 14px; margin-top: 6px; }
    .hint  { background: #fffde7; border-left: 4px solid #f9a825; padding: 10px; margin-top: 12px; }
    .work-area { margin-top: 20px; border: 1px dashed #aaa; min-height: 120px; padding: 8px; border-radius: 4px; }
    .work-label { font-size: 12px; color: #888; }
    footer { margin-top: 24px; font-size: 11px; color: #aaa; text-align: center; }
  </style>
</head>
<body>
  <h1>${world.guideEmoji} ${quest.questTitle || 'Quest Map'}</h1>
  <p class="hero">Quest for: <strong>${name}</strong> &nbsp;|&nbsp; World: ${world.name}</p>
  <p><em>${quest.objective || ''}</em></p>

  <div class="stage">
    <div class="stage-title">⚡ ${quest.stage1?.title || world.terms.stage1}</div>
    <div class="stage-body">${quest.stage1?.content || ''}</div>
  </div>
  <div class="stage">
    <div class="stage-title">⚔️ ${quest.stage2?.title || world.terms.stage2}</div>
    <div class="stage-body">${quest.stage2?.content || ''}</div>
  </div>
  <div class="stage">
    <div class="stage-title">🏆 ${quest.stage3?.title || world.terms.stage3}</div>
    <div class="stage-body">${quest.stage3?.content || ''}</div>
  </div>

  ${quest.hint ? `<div class="hint"><strong>💡 ${world.terms.hint}:</strong> ${quest.hint}</div>` : ''}

  <div class="work-area">
    <div class="work-label">✏️ Work Space — do your work here, then take a photo to submit!</div>
  </div>

  <footer>Generated by QuestLens • Turn Boring into Boss Levels</footer>
</body>
</html>`;
}
